import test from 'node:test'; import assert from 'node:assert/strict';
import publicList from '../api/resources/index.js'; import download from '../api/resources/[id]/download.js'; import staffResources from '../api/staff/resources/index.js'; import staffRecord from '../api/staff/resources/[id].js';
function res(){return {statusCode:200,headers:{},body:null,setHeader(k,v){this.headers[k]=v},status(n){this.statusCode=n;return this},json(v){this.body=v;return this},redirect(n,url){this.statusCode=n;this.headers.Location=url;return this}}}
const published={id:'rec1',fields:{Title:'Guide',Summary:'Accessible summary for everyone.',Country:'Ghana',Topic:'Policy',Language:'English','Accessibility notes':'Tagged PDF',Attachment:[{filename:'guide.pdf',type:'application/pdf',size:1200,url:'https://dl.airtable.com/file'}],'Publication status':'Published','Updated at':'2026-08-04T12:00:00Z'}};
test('public list maps Published records and caches briefly',async()=>{const out=res();await publicList({method:'GET'},out,{airtable:{listPublished:async()=>[published]}});assert.equal(out.body.resources[0].downloadUrl,'/api/resources/rec1/download');assert.match(out.headers['Cache-Control'],/s-maxage/)});
test('download refuses Draft records',async()=>{const out=res();await download({method:'GET',query:{id:'rec2'}},out,{airtable:{get:async()=>({id:'rec2',fields:{'Publication status':'Draft',Attachment:[{url:'https://private'}]}})}});assert.equal(out.statusCode,404)});
test('anonymous staff mutations are rejected',async()=>{const out=res();await staffResources({method:'POST',headers:{}},out,{session:async()=>null});assert.equal(out.statusCode,401)});
test('authenticated upload creates record then attachment',async()=>{const calls=[];const out=res();await staffResources({method:'POST',headers:{}},out,{session:async()=>({name:'Fadila Lagadien — BeAccessible'}),parseUpload:async()=>({fields:{title:'Guide',summary:'Accessible summary for everyone.',country:'Ghana',topic:'Policy',language:'English',accessibility:'Tagged PDF',publicationStatus:'Published'},file:{name:'guide.pdf',type:'application/pdf',size:3,buffer:Buffer.from('pdf')}}),airtable:{create:async fields=>{calls.push(['create',fields]);return{id:'rec1',fields}},uploadAttachment:async(id,file)=>{calls.push(['upload',id,file.name]);return{}},get:async()=>published}});assert.equal(out.statusCode,201);assert.deepEqual(calls.map(x=>x[0]),['create','upload']);assert.equal(calls[0][1]['Created by'],'Fadila Lagadien — BeAccessible')});
test('authenticated record deletion uses the exact id',async()=>{let deleted;const out=res();await staffRecord({method:'DELETE',query:{id:'rec%201'},headers:{}},out,{session:async()=>({name:'Fadila'}),airtable:{delete:async id=>{deleted=id;return{id}}}});assert.equal(deleted,'rec%201');assert.equal(out.statusCode,200)});
