export const DEMO_DATA = Object.freeze({
  countries: [
    { id: 'north-coast', name: 'North Coast Region', member: 'Harbour Access Collective', summary: 'Illustrative member organisation coordinating accessible community services and shared advocacy.', status: 'Active', progress: 68, milestones: 8 },
    { id: 'central-plains', name: 'Central Plains Region', member: 'Open Path Association', summary: 'Illustrative member organisation strengthening participation, peer learning and regional collaboration.', status: 'Active', progress: 61, milestones: 6 },
    { id: 'lakeside', name: 'Lakeside Region', member: 'Bridgeway Network', summary: 'Illustrative member organisation connecting evidence, programme delivery and member-led learning.', status: 'Active', progress: 74, milestones: 9 },
    { id: 'southern-highlands', name: 'Southern Highlands Region', member: 'Common Ground Forum', summary: 'Illustrative member organisation advancing accountable programmes and partnership practice.', status: 'Active', progress: 57, milestones: 7 }
  ],
  policies: [
    { id: 'p1', title: 'Member Participation Framework', country: 'North Coast Region', status: 'In progress', framework: 'Network standard', updated: '18 August 2026', partner: 'Harbour Access Collective (fictional)', summary: 'Tracks participation commitments, evidence, responsibilities and follow-up actions.' },
    { id: 'p2', title: 'Accessible Communications Programme', country: 'Central Plains Region', status: 'Consultation', framework: 'Programme plan', updated: '11 August 2026', partner: 'Open Path Association (fictional)', summary: 'Records work to improve accessible formats, member communications and feedback pathways.' },
    { id: 'p3', title: 'Shared Learning Programme', country: 'Lakeside Region', status: 'On track', framework: 'Network standard', updated: '24 August 2026', partner: 'Bridgeway Network (fictional)', summary: 'Monitors inclusive learning commitments and implementation evidence across member teams.' },
    { id: 'p4', title: 'Inclusive Services Review', country: 'Southern Highlands Region', status: 'Evidence review', framework: 'Programme plan', updated: '19 August 2026', partner: 'Common Ground Forum (fictional)', summary: 'Connects service commitments to illustrative programme activity and member feedback.' },
    { id: 'p5', title: 'Annual Member Evidence Cycle', country: 'North Coast Region', status: 'On track', framework: 'Network standard', updated: '25 August 2026', partner: 'Harbour Access Collective (fictional)', summary: 'Tracks milestone evidence, owners, review dates and agreed next actions.' },
    { id: 'p6', title: 'Regional Partnership Plan', country: 'Lakeside Region', status: 'Consultation', framework: 'Partnership plan', updated: '21 August 2026', partner: 'Bridgeway Network (fictional)', summary: 'Documents partnership milestones, member participation and follow-up commitments.' }
  ],
  resources: [
    { id: 'r1', title: 'Member Progress Tracking Starter Guide', country: 'All regions', topic: 'Monitoring', language: 'English', format: 'Guide', summary: 'Illustrative guide to recording milestones, evidence, owners, dates and next actions.', accessibility: 'Structured headings; plain-language summary; large-text ready.' },
    { id: 'r2', title: 'Guide de participation des membres', country: 'Central Plains Region', topic: 'Participation', language: 'French', format: 'Guide', summary: 'Ressource fictive illustrant la préparation d’une participation inclusive des organisations membres.', accessibility: 'Structure accessible; traduction illustrative.' },
    { id: 'r3', title: 'Regional Milestone Reporting Template', country: 'North Coast Region', topic: 'Monitoring', language: 'English', format: 'Template', summary: 'Illustrative template for milestones, evidence, responsibility and review dates.', accessibility: 'Accessible form structure and clear instructions.' },
    { id: 'r4', title: 'Inclusive Member Engagement Brief', country: 'Southern Highlands Region', topic: 'Participation', language: 'English', format: 'Brief', summary: 'Illustrative briefing for umbrella and member-organisation teams.', accessibility: 'Text alternatives and accessible-document checklist.' },
    { id: 'r5', title: 'Shared Learning Facilitation Notes', country: 'Lakeside Region', topic: 'Learning', language: 'English', format: 'Training', summary: 'Illustrative notes for accessible member learning and professional development sessions.', accessibility: 'Transcript-ready and low-data text edition.' },
    { id: 'r6', title: 'Member Partnership Checklist', country: 'All regions', topic: 'Partnership', language: 'English', format: 'Checklist', summary: 'Illustrative lightweight checklist for inclusive umbrella-to-member collaboration.', accessibility: 'Plain language and large-print ready.' }
  ]
});
